# Generated by Django 2.2.2 on 2019-06-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50, verbose_name='사이트 이름')),
                ('site_url', models.URLField(verbose_name='URL')),
            ],
        ),
    ]
