# Generated by Django 2.2.2 on 2019-06-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_rename_bookmark_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50, verbose_name='사이트 이름')),
                ('site_url', models.URLField(verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=50, verbose_name='리스트 이름')),
                ('description', models.CharField(max_length=255, verbose_name='설명')),
                ('access_level', models.CharField(choices=[('P', '개인'), ('S', '공개')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='bookmark_item',
        ),
        migrations.AddField(
            model_name='bookmarkitem',
            name='belonged_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmark.BookmarkList'),
        ),
    ]
