# Generated by Django 2.2.2 on 2019-06-13 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmark', '0004_auto_20190613_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarklist',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookmarkitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='bookmarkitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='bookmarklist',
            name='access_level',
            field=models.CharField(choices=[('P', '개인'), ('S', '공개')], default='P', max_length=1, verbose_name='접근 권한'),
        ),
        migrations.AlterField(
            model_name='bookmarklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='bookmarklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 시간'),
        ),
    ]
