# Generated by Django 2.2.2 on 2019-06-21 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0005_auto_20190613_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarklist',
            name='user',
            field=models.ManyToManyField(related_name='own_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
