# Generated by Django 2.2.2 on 2019-06-18 20:52

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(error_messages={'unique': '해당 닉네임은 이미 존재합니다.'}, help_text='필수 항목. 36자 이하로 영문자, 숫자, - 또는 _만 사용 가능합니다.', max_length=36, unique=True, validators=[accounts.models.UsernameValidator()], verbose_name='닉네임'),
        ),
    ]
