# Generated by Django 2.2.2 on 2019-06-21 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0006_auto_20190621_1606'),
        ('accounts', '0005_auto_20190620_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_items',
            field=models.ManyToManyField(related_name='fan_of_item', to='bookmark.BookmarkList'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_lists',
            field=models.ManyToManyField(related_name='fan_of_list', to='bookmark.BookmarkList'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(related_name='_userprofile_followers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followings',
            field=models.ManyToManyField(related_name='_userprofile_followings_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='profile_images/no_image.png', upload_to='profile_images/', verbose_name='프로필 이미지'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state_message',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='상태 메시지'),
        ),
    ]
