# Generated by Django 2.2.2 on 2019-06-21 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190621_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_items',
            field=models.ManyToManyField(blank=True, null=True, related_name='fan_of_item', to='bookmark.BookmarkList'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_lists',
            field=models.ManyToManyField(blank=True, null=True, related_name='fan_of_list', to='bookmark.BookmarkList'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='_userprofile_followers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='followings',
            field=models.ManyToManyField(blank=True, null=True, related_name='_userprofile_followings_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
