# Generated by Django 2.2.2 on 2019-06-23 19:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190621_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_items',
            field=models.ManyToManyField(blank=True, null=True, related_name='fan_of_item', to='bookmark.BookmarkItem'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='profile_images/no_image.png', upload_to=accounts.models.UserProfile._upload_to, verbose_name='프로필 이미지'),
        ),
    ]
